
package ar.com.ejb.ws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeServiceWS", targetNamespace = "http://servicio.ejb.apress.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeServiceWS {


    /**
     * 
     * @return
     *     returns java.util.List<ar.com.ejb.ws.client.Employee>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarEmployees", targetNamespace = "http://servicio.ejb.apress.com/", className = "ar.com.ejb.ws.client.ListarEmployees")
    @ResponseWrapper(localName = "listarEmployeesResponse", targetNamespace = "http://servicio.ejb.apress.com/", className = "ar.com.ejb.ws.client.ListarEmployeesResponse")
    @Action(input = "http://servicio.ejb.apress.com/EmployeeServiceWS/listarEmployeesRequest", output = "http://servicio.ejb.apress.com/EmployeeServiceWS/listarEmployeesResponse")
    public List<Employee> listarEmployees();

    /**
     * 
     * @return
     *     returns java.util.List<ar.com.ejb.ws.client.PartTimeEmployee>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarPartTimeEmployees", targetNamespace = "http://servicio.ejb.apress.com/", className = "ar.com.ejb.ws.client.ListarPartTimeEmployees")
    @ResponseWrapper(localName = "listarPartTimeEmployeesResponse", targetNamespace = "http://servicio.ejb.apress.com/", className = "ar.com.ejb.ws.client.ListarPartTimeEmployeesResponse")
    @Action(input = "http://servicio.ejb.apress.com/EmployeeServiceWS/listarPartTimeEmployeesRequest", output = "http://servicio.ejb.apress.com/EmployeeServiceWS/listarPartTimeEmployeesResponse")
    public List<PartTimeEmployee> listarPartTimeEmployees();

    /**
     * 
     * @return
     *     returns java.util.List<ar.com.ejb.ws.client.FullTimeEmployee>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarFullTimeEmployees", targetNamespace = "http://servicio.ejb.apress.com/", className = "ar.com.ejb.ws.client.ListarFullTimeEmployees")
    @ResponseWrapper(localName = "listarFullTimeEmployeesResponse", targetNamespace = "http://servicio.ejb.apress.com/", className = "ar.com.ejb.ws.client.ListarFullTimeEmployeesResponse")
    @Action(input = "http://servicio.ejb.apress.com/EmployeeServiceWS/listarFullTimeEmployeesRequest", output = "http://servicio.ejb.apress.com/EmployeeServiceWS/listarFullTimeEmployeesResponse")
    public List<FullTimeEmployee> listarFullTimeEmployees();

}
